### PR TITLE
sp1-3: Create Roles model and repository

### PR DESCRIPTION
**Pull request by aesaries**
Role Entity

### CODE REVIEW

**Comment by aesaries** [comment]
send commits

**Review by aesaries — COMMENTED** [review]
ok

**Review by aesaries — COMMENTED** [review]
ok

**Review by agustin-kiryk — CHANGES_REQUESTED** [review]
linea 18 cambiar a  "ROLES"

**Review by agustin-kiryk — APPROVED** [review]

**Comment by agustin-kiryk** [comment]
Ok!

**Review by JeremiasOviedo — APPROVED** [review]

**Pull request merged**
